language: java
jdk: 
  - openjdk8

script:
  - ./gradlew clean jar
  - echo "testing coming soon"

  after_success:
  - "./gradlew jacocoTestReport"
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}